/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package driver.ci.pipeline;

import org.junit.jupiter.api.Test;
//import static org.junit.jupiter.api.Assertions.*;
//import assignment.*;

class UniDataTest {
    @Test void appHasAGreeting() {
        //Probably don't need this test file
    }
}
